// Auto-generated by scripts/generate-eslint-react-types.mts
// Do not edit manually

export type ESLintReactPluginNames =
  | '@eslint-react'
  | '@eslint-react/rsc'
  | '@eslint-react/dom'
  | '@eslint-react/hooks-extra'
  | '@eslint-react/naming-convention'
  | '@eslint-react/web-api';
