import fs from 'node:fs/promises';
import path from 'node:path';

import eslintPluginReact from '@eslint-react/eslint-plugin';
import * as prettier from 'prettier';

const pluginNames = Object.keys(
  (eslintPluginReact.configs.all as unknown as { plugins: object }).plugins,
);

export const outputPath = path.resolve(
  import.meta.dirname,
  '../src/plugins/types/eslint-react-plugin-names.generated.ts',
);

export async function generateTypeContent(): Promise<string> {
  const content = `// Auto-generated by scripts/generate-eslint-react-types.mts
// Do not edit manually

export type ESLintReactPluginNames =
${pluginNames.map((name) => `  | '${name}'`).join('\n')};
`;

  return await prettier.format(content, {
    ...(await prettier.resolveConfig(outputPath)),
    filepath: outputPath,
  });
}

// Only write to file when run directly (not imported as a module)
if (import.meta.filename === process.argv[1]) {
  const content = await generateTypeContent();
  await fs.writeFile(outputPath, content);
  console.log(`Generated ${outputPath}`);
}
